dist: trusty
language: node_js
node_js:
  - "stable"
before_script:
  - cd alurapic/
script:
  - npm install
after_success:
  - npm run dev
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: teste-ci-vue-gustavo
