dist: trusty
language: node_js
node_js:
  - "stable"
before_script:
  - cd alurapic/
  - npm install
script:
  - npm run dev
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: test-ci-gustavo
